version: '3.5'

services:
  init:
    container_name: init
    image: confluentinc/cp-kafka:7.2.2
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      /etc/scripts/init.sh
      "
    env_file:
      - ./env_files/init.env
    networks:
      - kafkastreams-network
    volumes:
      - ./conf:/etc/kafka/secrets
      - ./scripts:/etc/scripts

networks:
  kafkastreams-network:
    name: ks
