version: '3.5'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.2.2
    ports:
      - "2181:2181"
    env_file:
      - ./env_files/zk.env
    networks:
      - kafkastreams-network
    volumes:
      - ./conf:/etc/kafka/secrets

  broker:
    container_name: broker
    image: confluentinc/cp-kafka:7.2.2
    depends_on:
      - zookeeper
    ports:
      - "29093:29093"
    env_file:
      - ./env_files/kafka.env
    networks:
      - kafkastreams-network
    volumes:
      - ./conf:/etc/kafka/secrets

networks:
  kafkastreams-network:
    name: ks
