version: '3.5'

services:
  registry:
    container_name: registry
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/registry:${REGISTRY_TAG:-latest}
    ports:
      - 5000:5000
    networks:
      - core
    restart: always

  zookeeper:
    container_name: zookeeper
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/zookeeper:${ZOOKEEPER_TAG:-latest}
    depends_on:
      - registry
    ports:
      - "2181:2181"
    env_file:
      - ./env_files/zk.env
    networks:
      - core
    restart: always

  broker:
    container_name: broker
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/kafka:${KAFKA_TAG:-latest}
    depends_on:
      - registry
      - zookeeper
    ports:
      - "29093:29093"
    env_file:
      - ./env_files/kafka.env
    networks:
      - core
    restart: always

networks:
  core:
    name: core
