version: '3.5'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.2.2
    ports:
      - "2181:2181"
    env_file:
      - ./env_files/zk.env
    networks:
      - kafkastreams-network
    volumes:
      - ./conf:/etc/kafka/secrets

  broker:
    container_name: broker
    image: confluentinc/cp-kafka:7.2.2
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "29093:29093"
    env_file:
      - ./env_files/kafka.env
    networks:
      - kafkastreams-network
    volumes:
      - ./conf:/etc/kafka/secrets

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=Asia/Kolkata
    ports:
      - "1880:1880"
    networks:
      - kafkastreams-network
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:

networks:
  kafkastreams-network:
    name: ks
