version: '3.5'

services:
  cleaner:
    container_name: mitra-cleaner-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/cleaner:${CLEANER_TAG:-latest}
    env_file:
      - cleaner.env
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:8080/health || exit 1
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 10s
    networks:
      - kafkastreams-network

  limits:
    container_name: mitra-limits-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/limits:${LIMITS_TAG:-latest}
    env_file:
      - limits.env
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:8080/health || exit 1
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 10s
    networks:
      - kafkastreams-network

  alarms:
    container_name: mitra-alarms-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/alarms:${ALERTS_TAG:-latest}
    env_file:
      - alarms.env
    networks:
      - kafkastreams-network

  alerts:
    container_name: mitra-alerts-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/alerts:${ALARMS_TAG:-latest}
    env_file:
      - alerts.env
    networks:
      - kafkastreams-network

  merger:
    container_name: mitra-merger-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/merger:${MERGER_TAG:-latest}
    env_file:
      - merger.env
    networks:
      - kafkastreams-network

  streamer:
    container_name: mitra-streamer-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/streamer:${STREAMER_TAG:-latest}
    env_file:
      - streamer.env
    ports:
      - "8080:8080"
    networks:
      - kafkastreams-network

networks:
  kafkastreams-network:
    name: ks
